name: Create New Blog Post

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new-post]

permissions:
  contents: write

jobs:
  create_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new markdown file
        run: |
          DATE=$(date -u +"%Y-%m-%d-%H-%M")
          FILE="posts/${DATE}.md"
          echo -e "---\ntitle: New Post\ndate: $(date -u +"%Y-%m-%dT%H:%M:%SZ")\ntags: []\n---\n\nWrite your content here." > $FILE

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/
          git commit -m "Create new post: ${DATE}.md"
          git push origin ${GITHUB_REF_NAME}
