name: Update Posts Index

on:
  push:
    paths:
      - 'posts/*.md'
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Update posts index
        run: |
          cd posts
          echo "{" > index.json
          echo "  \"posts\": [" >> index.json
          ls -1 *.md | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >> index.json
          echo "  ]" >> index.json
          echo "}" >> index.json
          cd ..

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posts/index.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update posts index" && git push)
